### ISSUE TITLE
BepinEx 6.0.0 Build 571 required??

### ISSUE THREAD

**Issue by dmjohn0x** [Silvris/Magicite#5]
Several mods for the latest update of PR requires BepinEX v6.0.0 Build 577. Any way we can get Magicite updated to work properly on it? As I dont think its possible to run multiple versions/instances of BepinEX in order to satisfy various requirements for specific mods.

**Comment by Silvris** [comment]
577 should work. I'm not sure why Saftle chose 571, as the breaking change occurred in 647.
